//LABORATÓRIO DE PROGRAMAÇÃO 1
export const LP1 = [
    '01 - Apresentação do Curso',
    '02 - Introdução a Algoritmo',
    '03 - Fluxograma',
    '04 - Codeblocks e C',
    '05 - Variável ',
    '06 - Variável  - Prática',
    '07 - Operações Aritméticas ',
    '08 - Operações Aritméticas - Prática',
    '09 - Trabalho Fluxograma',
    '10 - Trabalho Fluxograma',
    '11 - Prova I',
    '12 - Prova I',
    '13 - Correção',
    '14 - Estrutura de Decisão - IF ',
    '15 - Estrutura de Decisão - Operador Ternário e Operação Lógicos (E/OU)',
    '16 - Estrutura de Decisão - Switch',
    '17 - Estrutura de Decisão - Atividade',
    '18 - Estrutura de Repetição - FOR',
    '19 - Estrutura de Repetição - WHILE e DO-WHILE',
    '20 - Estrutura de Repetição - Break e Continue',
    '21 - Estrutura de Repetição - Atividade',
    '22 - Revisão',
    '23 - Prova II',
    '24 - Prova II',
    '25 - Correção da Prova',
    '26 - Procedure/Function',
    '27 - Procedure/Function - Atividade',
    '28 - Vetores/Matriz',
    '29 - Vetores/Matriz - Atividade',
    '30 - Sorteio dos Trabalhos',
    '31 - Acompanhar Projeto',
    '32 - Acompanhar Projeto',
    '33 - Acompanhar Projeto',
    '34 - Acompanhar Projeto',
    '35 - Acompanhar Projeto',
    '36 - Acompanhar Projeto',
    '37 - Acompanhar Projeto',
    '38 -  Acompanhar Projeto',
    '39 - Acompanhar Projeto',
    '40 - Entrega de Notas e Tirar Duvidas'
];

//LABORATÓRIO DE BANCO DE DADOS
export const LBD = [
    '01 - Oracle - Introdução',
    '02 - DDL',
    '03 - DQL - SELECT',
    '04 - DQL - Group By Having',
    '05 - DML - DELETE, INSERT, UPDATE',
    '06 - Joins',
    '07 - Revisão',
    '08 - Atividade de Revisão - Tirar Duvidas',
    '09 - Criando Campos Indexados',
    '10 - Segurança',
    '11 - Views',
    '12 - Atividade',
    '13 - PROVA I',
    '14 - Atividade para ajuste de nota ',
    '15 - Procedure',
    '16 - Procedure',
    '17 - Procedure',
    '18 - Procedure ',
    '19 - Praticando',
    '20 - Atividade',
    '21 - Revisão',
    '22 - Trigger',
    '23 - Trigger',
    '24 - Trigger',
    '25 - PROVA II',
    '26 - Correção de Prova',
    '27 - Atividade de revisão ',
    '28 - Introdução a Integridade, Integridade de Semântica',
    '29 - Integridade de Domínio',
    '30 - Integridade de Entidade',
    '31 - ntegridade de Referencia',
    '32 - Concorrência',
    '33 - Concorrência',
    '34 - Crashs e Falhas e Banco de Dados Distribuídos',
    '35 - Entrega de Trabalhos (NoSQL, BigData, Cloud Database, ETL) ',
    '36 - Atividade Integridade',
    '37 - Apresentação do Trabalho',
    '38 - PROVA III',
    '39 - Atividade para ajudar nota',
    '40 - Entrega de nota'
]

//INTELIGENCIA ARTIFICIAL
export const IA = [
    '01 - Introdução',
    '02 - Revisão de Python (Criar objetos, Pass, Privado, Documentação e Importar Classe)',
    '03 - Introdução a Heuristica e Algoritmos de Busca ',
    '04 - Algoritmo Genético (Teoria)',
    '05 - Algoritmo Genético - Resolvendo Problemas Binários',
    '06 - Algoritmo Genético - Tirar Dúvidas de Atividade',
    '07 - Algoritmo Genético - Resolvendo Problemas Valor',
    '08 - Algoritmo Genético - Tirar Dúvidas de Atividade',
    '09 - Algoritmo Genético - Permutação',
    '10 - Algoritmo Genético - Tirar Dúvidas de Atividade',
    '11 - Sistemas Especialistas e Revisão',
    '12 - Fazer atividades pendentes (Segunda chamada)',
    '13 - Prova I',
    '14 - Correção da Prova ',
    '15 - Machine Learning (Teoria)',
    '16 - Classificação (NeaviByeis KNN e Arvore de DEcisão)',
    '17 - Classificação (Atividade)',
    '18 - Regressão (Linear) ',
    '19 - Atividade Regressão (Linear)',
    '20 - Agrupamento (Kmeans)',
    '21 - Encontro para tirar duvidas  - Extra',
    '22 - Redes Neurais / Deep Learning (Teoria - Matemática) ',
    '23 - Redes Neurais Prática (Kera com Classificação Binária)',
    '24 - Atividade',
    '25 - PROVA II',
    '26 - Correção de Prova',
    '27 - Revisão',    
    '28 - Processamento de Linguagem Natural (spacy)',
    '29 - Análise de Sentimentos (Teoria / Prática - Polaridade - Dicionário - Léxico - BIblioteca TextBlob - googletrans) Análise de Sentimentos (Criando nossa própria Biblioteca)',
    '30 - Chatbot',
    '31 - Criando um Assistente Virtual Alexa',
    '32 - Separar trabalhos e grupos',
    '33 - Apresentação de trabalhos',
    '34 - Apresentação de Trabalhos',
    '35 - Entrega de Trabalho',
    '36 - Trabalho complementar',
    '37 - Revisão', 
    '38 - Prova III',
    '39 - Entrega de Notas',
    '40 - Trabalho para melhoria de nota (19/06)',
]

//SISTEMAS MULTIMIDIAS
export const SM = [
    '01 - Introdução a desenvolvimento de Jogos ',
    '02 - GDD',
    '03 - Conceitos',
    '04 - Áudio',
    '05 - 2D - Sprites',
    '06 - 3D - Fuse e Mixamo',
    '07 - Tirar Dúvidas',
    '08 - Tirar Dúvidas',
    '09 - Tirar Dúvidas',
    '10 - Apresentar Projeto',
    '11 - Apresentar Projeto',
    '12 - Unity Instalando, Interface, Build do jogo ',
    '13 - Criando Personagem, fisica',
    '14 - Codificante a movimentação do personagem',
    '15 - Animação',
    '16 - Tilesets',
    '17 - Inimigos',
    '18 - Interface - HUD',
    '19 - Áudios',
    '20 - PlayerPrefs',
    '21 - Tirar Dúvidas',
    '22 - Tirar Dúvidas',
    '23 - tirar dúvidas',
    '24 - tirar dúvidas',
    '25 - Apresentação',
    '26 - Apresentação',
    '27 - Criando Cenário Terrain e ProBuilder',
    '28 - Adicionando Personagem (Animação e Baixando Script)',
    '29 - Câmera seguindo personagem e NavMesh',
    '30 - Desenvolver Projeto',
    '31 - Desenvolver Projeto',
    '32 - Desenvolver Projeto',
    '33 - Tirar Dúvidas',
    '34 - Tirar Dúvidas', 
    '35 - Tirar Dúvidas', 
    '36 - Tirar Dúvidas',
    '37 - Tirar duvidas',
    '38 - Apresentação de Trabalhos',
    '39 - Apresentação de Trabalhos',
    '40 - Entrega de Notas',
]

//LABORATÓRIO DE PROGRAMAÇÃO 6
export const LP6 = [
    '01 - Introdução a Dispositivos Móveis',
    '02 - Visual Studio Code, NPM e TypeScript',
    '03 - EXPO',
    '04 - Componentes ',
    '05 - Montando Tela Login',
    '06 - State',
    '07 - Props',
    '08 - Formik e Yup',
    '09 - Tirar Dúvidas',
    '10 - Tirar Dúvida',
    '11 - Prova I',
    '12 - Trabalho para compor nota',
    '13 - Expo Router - Stack Navigation',
    '14 - Expo Router - Drawer / Bottom Navigation',
    '15 - FlatList e Map',
    '16 - Alert, Toast e Modalize',
    '17 - Recursos Nativo',
    '18 - ContextAPI',
    '19 - Tirar duvidas',
    '20 - Tirar duvidas',
    '21 - Tirar Dúvidas',
    '22 - Tirar Dúvidas',
    '23 - Tirar Dúvidas',
    '24 - Tirar Duvidas',
    '25 - Apresentação',
    '26 - Apresentação ',
    '27 - WebService - Teórico',
    '28 - Axios (API)',
    '29 - Firebase Login',
    '30 - Firebase Banco - FireStore',
    '31 - Recursos Nativo (Admob) e Push Notification',
    '32 - Gerando APK e publicando na Loja',
    '33 - Tirar Dúvidas', 
    '34 - Tirar Dúvidas',
    '35 - Tirar Dúvidas',
    '36 - Tirar Dúvidas',
    '37 - Apresentação',
    '38 - Apresentação de Trabalho',
    '39 - Tirar dúvidas',
    '40 - Entrega de Notas',
]

//PADRÕES DE PROJETO
export const PP = [
    '01 - Introdução a Padrões de Projeto e Abstract Factory',
    '02 - Revisão e Padrão Builder',
    '03 - Padrão Factory Method ',
    '04 - Singleton e Prototype',
    '05 - Revisão',
    '06 - Prova I',
    '07 - Correção da Prova e Adapter',
    '08 - Bridge, Composite',
    '09 - Decorator, Facade ',
    '10 - Flyweight e Proxy',
    '11 - Revisão',
    '12 - PROVA II',
    '13 - ATIVIDADE EXTRA',
    '14 - Correção da prova e Divisão de trabalhos',
    '15 - Chain of Responsability, Command',
    '16 - Interpreter, Iterator ',
    '17 - Mediator, Memento',
    '18 - State e Strategy',
    '19 - Observable, Visitor, Template Method',
    '20 - Entrega das notas',
]